### ISSUE TITLE
Exiting from tunnel issue

### ISSUE THREAD

**Issue by bgh716** [bgh716/TrainTunnel#7]
collision happening when train is entering to rail and other train exiting from tunnel at the same time

**Comment by postopian** [comment]
Pretend tunnel exit always has a leaving train, blocking the signal connecting to the tunnel exit
 - Need to place a dummy train at the starting position of tunnel exit(marked as orange)
 - Creating train leaving the tunnel does not matter, since collision boxes do not overlap
![image](https://user-images.githubusercontent.com/47389405/235341982-06152562-fef7-439a-9b36-89cafc9ec27b.png)

**Comment by bgh716** [comment]
#### bug fixed
  - placed temp train 2 on exit side, but we need to adjust the signal position to block trains entering from other lanes

**Comment by bgh716** [comment]
#### Exit detects trains, and if there is some rolling stocks, the exit is under pending by signal and detection
